apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-service
  template:
    metadata:
      labels:
        app: resources-service
    spec:
      containers:
        - name: resources-service
          image: resources-service:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka:8761/eureka"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres-svc:5432/resources" # start using postgres statefulset
              #value: "jdbc:postgresql://postgres:5432/resources"
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: spring.jpa.hibernate.ddl-auto
              value: "update"
