apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: k8s-program
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka-server
          image: eureka-server:k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
